# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print_calc_worked_beta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 390)
        MainWindow.setMinimumSize(QtCore.QSize(500, 390))
        MainWindow.setMaximumSize(QtCore.QSize(500, 390))

        self.fontSmall = QtGui.QFont()
        self.fontSmall.setPointSize(10)
        self.fontSmall.setFamily("MS Shell Dlg 2")
        self.fontBig = QtGui.QFont()
        self.fontBig.setPointSize(14)
        self.fontBig.setFamily("MS Shell Dlg 2")

        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -1, 502, 392))
        self.tabWidget.setObjectName("tabWidget")

        self.calc = QtWidgets.QWidget()
        self.calc.setObjectName("calc")

        self.modelSwitch = QtWidgets.QCheckBox(self.calc)
        self.modelSwitch.setGeometry(QtCore.QRect(10, 290, 91, 16))
        self.modelSwitch.setFont(self.fontSmall)
        self.modelSwitch.setObjectName("modelSwitch")

        self.modelLabel = QtWidgets.QLabel(self.calc)
        self.modelLabel.setGeometry(QtCore.QRect(10, 310, 181, 16))
        self.modelLabel.setFont(self.fontSmall)
        self.modelLabel.setObjectName("modelLabel")

        self.postprocessingLabel = QtWidgets.QLabel(self.calc)
        self.postprocessingLabel.setGeometry(QtCore.QRect(10, 150, 161, 16))

        self.postprocessingLabel.setFont(self.fontSmall)
        self.postprocessingLabel.setObjectName("postprocessingLabel")

        self.massEdit = QtWidgets.QLineEdit(self.calc)
        self.massEdit.setGeometry(QtCore.QRect(10, 39, 181, 21))
        self.massEdit.setObjectName("massEdit")

        self.prototypeEdit = QtWidgets.QLineEdit(self.calc)
        self.prototypeEdit.setEnabled(False)
        self.prototypeEdit.setGeometry(QtCore.QRect(10, 250, 181, 21))
        self.prototypeEdit.setObjectName("prototypeEdit")

        self.postprocessingSwitch = QtWidgets.QCheckBox(self.calc)
        self.postprocessingSwitch.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.postprocessingSwitch.setFont(self.fontSmall)
        self.postprocessingSwitch.setObjectName("postprocessingSwitch")

        self.massLabel = QtWidgets.QLabel(self.calc)
        self.massLabel.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.massLabel.setFont(self.fontSmall)
        self.massLabel.setObjectName("massLabel")

        self.modelEdit = QtWidgets.QLineEdit(self.calc)
        self.modelEdit.setEnabled(False)
        self.modelEdit.setGeometry(QtCore.QRect(10, 330, 181, 21))
        self.modelEdit.setObjectName("modelEdit")

        self.prototypeLabel = QtWidgets.QLabel(self.calc)
        self.prototypeLabel.setGeometry(QtCore.QRect(10, 230, 181, 16))
        self.prototypeLabel.setFont(self.fontSmall)
        self.prototypeLabel.setObjectName("prototypeLabel")

        self.timeEdit = QtWidgets.QLineEdit(self.calc)
        self.timeEdit.setGeometry(QtCore.QRect(10, 91, 181, 21))
        self.timeEdit.setObjectName("timeEdit")

        self.prototypeSwitch = QtWidgets.QCheckBox(self.calc)
        self.prototypeSwitch.setGeometry(QtCore.QRect(10, 210, 81, 16))
        self.prototypeSwitch.setFont(self.fontSmall)
        self.prototypeSwitch.setObjectName("prototypeSwitch")

        self.timeLabel = QtWidgets.QLabel(self.calc)
        self.timeLabel.setGeometry(QtCore.QRect(10, 70, 141, 16))
        self.timeLabel.setFont(self.fontSmall)
        self.timeLabel.setObjectName("timeLabel")

        self.postprocessingEdit = QtWidgets.QLineEdit(self.calc)
        self.postprocessingEdit.setEnabled(False)
        self.postprocessingEdit.setGeometry(QtCore.QRect(10, 170, 181, 21))
        self.postprocessingEdit.setObjectName("postprocessingEdit")

        self.plastCh = QtWidgets.QComboBox(self.calc)
        self.plastCh.setGeometry(QtCore.QRect(230, 90, 181, 21))
        self.plastCh.setObjectName("plastCh")

        self.plastChLable = QtWidgets.QLabel(self.calc)
        self.plastChLable.setGeometry(QtCore.QRect(230, 70, 151, 16))
        self.plastChLable.setFont(self.fontSmall)
        self.plastChLable.setObjectName("plastChLable")

        self.calcButt = QtWidgets.QPushButton(self.calc)
        self.calcButt.setGeometry(QtCore.QRect(230, 140, 181, 41))

        self.calcButt.setFont(self.fontBig)
        self.calcButt.setObjectName("calcButt")

        self.amountLabel = QtWidgets.QLabel(self.calc)
        self.amountLabel.setGeometry(QtCore.QRect(230, 21, 151, 16))
        self.amountLabel.setFont(self.fontSmall)
        self.amountLabel.setObjectName("amountLabel")

        self.amountEdit = QtWidgets.QLineEdit(self.calc)
        self.amountEdit.setGeometry(QtCore.QRect(230, 40, 181, 21))
        self.amountEdit.setObjectName("amountEdit")

        self.calcOutput = QtWidgets.QTextEdit(self.calc)
        self.calcOutput.setGeometry(QtCore.QRect(230, 200, 241, 151))
        self.calcOutput.setObjectName("calcOutput")


        self.tabWidget.addTab(self.calc, "")
        self.plastics = QtWidgets.QWidget()
        self.plastics.setObjectName("plastics")

        self.plastNameEdit = QtWidgets.QLineEdit(self.plastics)
        self.plastNameEdit.setGeometry(QtCore.QRect(270, 40, 121, 21))
        self.plastNameEdit.setObjectName("plastNameEdit")

        self.plastNameLabel = QtWidgets.QLabel(self.plastics)
        self.plastNameLabel.setGeometry(QtCore.QRect(270, 20, 121, 16))
        self.plastNameLabel.setFont(self.fontSmall)
        self.plastNameLabel.setObjectName("plastNameLabel")

        self.plastPriceLabel = QtWidgets.QLabel(self.plastics)
        self.plastPriceLabel.setGeometry(QtCore.QRect(270, 80, 121, 16))
        self.plastPriceLabel.setFont(self.fontSmall)
        self.plastPriceLabel.setObjectName("plastPriceLabel")

        self.plastPriceEdit = QtWidgets.QLineEdit(self.plastics)
        self.plastPriceEdit.setGeometry(QtCore.QRect(270, 100, 121, 21))
        self.plastPriceEdit.setObjectName("plastPriceEdit")

        self.addPlastButt = QtWidgets.QPushButton(self.plastics)
        self.addPlastButt.setGeometry(QtCore.QRect(270, 140, 121, 31))
        self.addPlastButt.setObjectName("addPlastButt")

        self.delPlastButt = QtWidgets.QPushButton(self.plastics)
        self.delPlastButt.setGeometry(QtCore.QRect(270, 190, 121, 31))
        self.delPlastButt.setObjectName("delPlastButt")

        self.plastTable = QtWidgets.QTableWidget(self.plastics)
        self.plastTable.setGeometry(QtCore.QRect(10, 10, 240, 341))
        self.plastTable.setMinimumSize(QtCore.QSize(240, 341))
        self.plastTable.setMaximumSize(QtCore.QSize(240, 341))
        self.plastTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.plastTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.plastTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.plastTable.setColumnCount(2)
        self.plastTable.setObjectName("plastTable")
        self.plastTable.setRowCount(0)
        self.plastTable.verticalHeader().setVisible(False)


        self.tabWidget.addTab(self.plastics, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")

        self.paybackFactorLabel = QtWidgets.QLabel(self.settings)
        self.paybackFactorLabel.setGeometry(QtCore.QRect(10, 21, 151, 16))

        self.paybackFactorLabel.setFont(self.fontSmall)
        self.paybackFactorLabel.setObjectName("paybackFactorLabel")
        self.paybackFactorEdit = QtWidgets.QLineEdit(self.settings)
        self.paybackFactorEdit.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.paybackFactorEdit.setObjectName("paybackFactorEdit")

        self.difficultyFactorLabel = QtWidgets.QLabel(self.settings)
        self.difficultyFactorLabel.setGeometry(QtCore.QRect(10, 71, 151, 16))
        self.difficultyFactorLabel.setFont(self.fontSmall)
        self.difficultyFactorLabel.setObjectName("difficultyFactorLabel")

        self.difficultyFactorEdit = QtWidgets.QLineEdit(self.settings)
        self.difficultyFactorEdit.setGeometry(QtCore.QRect(10, 90, 181, 21))
        self.difficultyFactorEdit.setObjectName("difficultyFactorEdit")

        self.electricityPriceLabel = QtWidgets.QLabel(self.settings)
        self.electricityPriceLabel.setGeometry(QtCore.QRect(10, 121, 181, 16))
        self.electricityPriceLabel.setFont(self.fontSmall)
        self.electricityPriceLabel.setObjectName("electricityPriceLabel")

        self.electricityPriceEdit = QtWidgets.QLineEdit(self.settings)
        self.electricityPriceEdit.setGeometry(QtCore.QRect(10, 140, 181, 21))
        self.electricityPriceEdit.setObjectName("electricityPriceEdit")

        self.printerPowerLabel = QtWidgets.QLabel(self.settings)
        self.printerPowerLabel.setGeometry(QtCore.QRect(10, 171, 151, 16))
        self.printerPowerLabel.setFont(self.fontSmall)
        self.printerPowerLabel.setObjectName("printerPowerLabel")

        self.printerPowerEdit = QtWidgets.QLineEdit(self.settings)
        self.printerPowerEdit.setGeometry(QtCore.QRect(10, 190, 181, 21))
        self.printerPowerEdit.setObjectName("printerPowerEdit")

        self.amortLabel = QtWidgets.QLabel(self.settings)
        self.amortLabel.setGeometry(QtCore.QRect(10, 221, 151, 16))
        self.amortLabel.setFont(self.fontSmall)
        self.amortLabel.setObjectName("amortLabel")

        self.amortEdit = QtWidgets.QLineEdit(self.settings)
        self.amortEdit.setGeometry(QtCore.QRect(10, 240, 181, 21))
        self.amortEdit.setObjectName("amortEdit")

        self.saveSettButt = QtWidgets.QPushButton(self.settings)
        self.saveSettButt.setGeometry(QtCore.QRect(30, 280, 141, 31))
        self.saveSettButt.setObjectName("saveSettButt")

        self.tabWidget.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralWidget)


        self.plastTable.setColumnCount(2)
        self.plastTable.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem("Пластик"))
        self.plastTable.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem("Цена"))
        self.plastTable.setColumnWidth(0, 136)
        self.plastTable.setColumnWidth(1, 102)
        self.plastTable.horizontalHeader().setSectionResizeMode(2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.postprocessingSwitch.clicked['bool'].connect(self.postprocessingEdit.setEnabled)
        self.postprocessingSwitch.clicked['bool'].connect(self.postprocessingEdit.clear)
        self.prototypeSwitch.clicked['bool'].connect(self.prototypeEdit.setEnabled)
        self.prototypeSwitch.clicked['bool'].connect(self.prototypeEdit.clear)
        self.modelSwitch.clicked['bool'].connect(self.modelEdit.setEnabled)
        self.modelSwitch.clicked['bool'].connect(self.modelEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DPC"))
        self.modelSwitch.setText(_translate("MainWindow", "3D модель"))
        self.modelLabel.setText(_translate("MainWindow", "Стоимость моделирования"))
        self.postprocessingLabel.setText(_translate("MainWindow", "Стоимость постобработки"))
        self.postprocessingSwitch.setText(_translate("MainWindow", "Постобработка"))
        self.massLabel.setText(_translate("MainWindow", "Итотговая масса, грамм"))
        self.prototypeLabel.setText(_translate("MainWindow", "Стоимость прототипирования"))
        self.prototypeSwitch.setText(_translate("MainWindow", "Прототип"))
        self.timeLabel.setText(_translate("MainWindow", "Время печати, минуты"))
        self.plastChLable.setText(_translate("MainWindow", "Пластик"))
        self.calcButt.setText(_translate("MainWindow", "Рассчитать"))
        self.amountLabel.setText(_translate("MainWindow", "Количество"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calc), _translate("MainWindow", "Калькулятор"))
        self.plastNameLabel.setText(_translate("MainWindow", "Название пластика"))
        self.plastPriceLabel.setText(_translate("MainWindow", "Цена за килограмм"))
        self.addPlastButt.setText(_translate("MainWindow", "Добавить пластик"))
        self.delPlastButt.setText(_translate("MainWindow", "Удалить пластик"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plastics), _translate("MainWindow", "Пластики"))
        self.paybackFactorLabel.setText(_translate("MainWindow", "Коэффициент окупания"))
        self.difficultyFactorLabel.setText(_translate("MainWindow", "Коэффициент сложности"))
        self.electricityPriceLabel.setText(_translate("MainWindow", "Стоимость эл-ва, руб за КВт"))
        self.printerPowerLabel.setText(_translate("MainWindow", "Мощность принтера, Вт"))
        self.amortLabel.setText(_translate("MainWindow", "Амортизация, руб/час"))
        self.saveSettButt.setText(_translate("MainWindow", "Сохранить настройки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Настройки"))